name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  AVN_PRODUCT: "carta"
  # The default release, should be overridden in config.sh
  AVN_RELEASE: "latest"
  # The default platform, should be overridden in the platform binaries jobs below
  AVN_PLATFORM: "linux"

  AVN_GPG_PASSWORD: ${{ secrets.AVN_GPG_PASSWORD }}
  AVN_KEYSTORE_PASSWORD: ${{ secrets.AVN_KEYSTORE_PASSWORD }}
  AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
  AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}

  DISPLAY: ":99"
  GITHUB_REF: ${{ github.ref }}
  JAVA_VERSION: "25"
  MAVEN_PARMS: "-B -U -V --settings .github/settings.xml --file pom.xml"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5

      - name: Fetch CI/CD resources
        uses: actions/checkout@v5
        with:
          repository: avereon/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      # Required to render the product icon
      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{env.JAVA_DISTRO}}
          java-version: ${{env.JAVA_VERSION}}

      - name: Maven Repository Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Compile
        run: |
          mvn ${{env.MAVEN_PARMS}} compile

      - name: Unit Tests
        run: |
          mvn ${{env.MAVEN_PARMS}} test

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      - name: Upload Artifacts for Next Steps
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: target

  publish:
    needs: build
    name: Maven Publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stable' || github.base_ref == 'refs/heads/main' || github.base_ref == 'refs/heads/stable'
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5

      - name: Fetch CI/CD resources
        uses: actions/checkout@v5
        with:
          repository: avereon/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      # Required to render the product icon
      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{env.JAVA_DISTRO}}
          java-version: ${{env.JAVA_VERSION}}
          java-package: ${{env.JAVA_PACKAGE}}

      - name: Maven Repository Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          name: build
          path: target

      - name: Publish Arifacts
        run: |
          mvn ${{env.MAVEN_PARMS}} deploy -Dmaven.test.skip=true

      - name: Publish Icons
        run: |
          scp -B target/main/images/*product.png ${{env.AVN_REPO_USERNAME}}@avereon.com:${PRODUCT_DEPLOY_PATH} 2>&1

      - name: Publish JavaDoc
        run: |
          ssh -t ${{env.AVN_REPO_USERNAME}}@avereon.com "mkdir -p ${{env.JAVADOC_DEPLOY_PATH}};"
          if [ $? -ne 0 ]; then exit 1; fi
          scp -B target/${AVN_PRODUCT}-*-javadoc.jar ${{env.AVN_REPO_USERNAME}}@avereon.com:${{env.JAVADOC_DEPLOY_PATH}}/javadoc.jar 2>&1
          if [ $? -ne 0 ]; then exit 1; fi
          ssh -t ${{env.AVN_REPO_USERNAME}}@avereon.com "mkdir -p ${{env.JAVADOC_TARGET_PATH}};rm -rf ${{env.JAVADOC_TARGET_PATH}}/*;cd ${{env.JAVADOC_TARGET_PATH}};jar -xf ${{env.JAVADOC_DEPLOY_PATH}}/javadoc.jar;cd -;"
          if [ $? -ne 0 ]; then exit 1; fi

  screenshots1x:
    needs: build
    name: Screenshots 1x
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stable' || github.base_ref == 'refs/heads/main' || github.base_ref == 'refs/heads/stable'
    env:
      AVN_PLATFORM: "linux"
      XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5

      - name: Fetch CI/CD resources
        uses: actions/checkout@v5
        with:
          repository: avereon/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{env.JAVA_DISTRO}}
          java-version: ${{env.JAVA_VERSION}}
          java-package: ${{env.JAVA_PACKAGE}}

      - name: Maven Repository Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          name: build
          path: target

      - name: Generate Screenshots
        run: |
          mvn ${{env.MAVEN_PARMS}} -Dmaven.test.skip=true -Pscreenshots1x package

      - name: Publish Screenshots
        run: |
          ssh -t ${{env.AVN_REPO_USERNAME}}@avereon.com "mkdir -p /opt/avn/web/screenshots/mod/carta;"
          if [ $? -ne 0 ]; then exit 1; fi
          scp -Br target/screenshots/* ${{env.AVN_REPO_USERNAME}}@avereon.com:/opt/avn/web/screenshots/mod/carta 2>&1

  screenshots2x:
    needs: build
    name: Screenshots 2x
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stable' || github.base_ref == 'refs/heads/main' || github.base_ref == 'refs/heads/stable'
    env:
      AVN_PLATFORM: "linux"
      XVFB_PARMS: "-screen 0 3840x2160x24 -nolisten unix"
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5

      - name: Fetch CI/CD resources
        uses: actions/checkout@v5
        with:
          repository: avereon/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{env.JAVA_DISTRO}}
          java-version: ${{env.JAVA_VERSION}}
          java-package: ${{env.JAVA_PACKAGE}}

      - name: Maven Repository Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          name: build
          path: target

      - name: Generate Screenshots
        run: |
          mvn ${{env.MAVEN_PARMS}} -Dmaven.test.skip=true -Pscreenshots2x package

      - name: Publish Screenshots
        run: |
          ssh -t ${{env.AVN_REPO_USERNAME}}@avereon.com "mkdir -p /opt/avn/web/screenshots/mod/carta;"
          if [ $? -ne 0 ]; then exit 1; fi
          scp -Br target/screenshots/* ${{env.AVN_REPO_USERNAME}}@avereon.com:/opt/avn/web/screenshots/mod/carta 2>&1

  packs:
    needs: build
    name: Module Packs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stable' || github.base_ref == 'refs/heads/main' || github.base_ref == 'refs/heads/stable'
    env:
      AVN_PLATFORM: "linux"
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5

      - name: Fetch CI/CD resources
        uses: actions/checkout@v5
        with:
          repository: avereon/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{env.JAVA_DISTRO}}
          java-version: ${{env.JAVA_VERSION}}
          java-package: ${{env.JAVA_PACKAGE}}

      - name: Maven Repository Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          name: build
          path: target

      - name: UX Tests
        run: |
          mvn ${{env.MAVEN_PARMS}} verify -P testui

      - name: Generate Packs
        run: |
          mvn ${{env.MAVEN_PARMS}} verify -P packs -Dmaven.test.skip=true

      - name: Publish Product Pack
        run: |
          scp -B target/*product.jar ${{env.AVN_REPO_USERNAME}}@avereon.com:${PRODUCT_DEPLOY_PATH} 2>&1

      - name: Publish Product Card
        run: |
          scp -B target/main/java/META-INF/*.card ${{env.AVN_REPO_USERNAME}}@avereon.com:${PRODUCT_DEPLOY_PATH} 2>&1

